version: "3.2"

services:
  financial-transactions-api:
    image: financial-transactions-api
    build:
      context: FinancialTransactionsApi/
      dockerfile: ./Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
      - Sns_LocalMode=true
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database
    depends_on:
     - pdf-generator

  financial-transactions-api-test:
    image: financial-transactions-api-test
    build:
      context: .
      dockerfile: FinancialTransactionsApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - ELASTICSEARCH_DOMAIN_URL=http://financial-transactions-api-elasticsearch:9200 
      - Localstack_SnsServiceUrl=http://localstack:4566
    links:
      - dynamodb-database
      - financial-transactions-api-elasticsearch
      - localstack
    #networks:
    #  - elastic
    depends_on:
    #  #- kibana
      - financial-transactions-api-elasticsearch

  dynamodb-database:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000

  localstack:
    image: localstack/localstack
    hostname: awslocal    
    ports:
      - "4566:4566"      
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1                  
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack      
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  pdf-generator:
    image: pdf-api-generator
    container_name: pdf-api-generator
    build:
      context: .
      dockerfile: data/pdf/Dockerfile

  financial-transactions-api-elasticsearch:
    image: financial-transactions-api-elasticsearch
    container_name: financial-transactions-api-elasticsearch
    build:
      context: .
      dockerfile: data/elasticsearch/Dockerfile
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
       -  financial-transaction-api-esdata-test:/usr/share/elasticsearch/data
    #networks:
    #  - elastic
      
  
  kibana:
        image: docker.elastic.co/kibana/kibana:7.9.3
        ports:
            - "5601:5601"
        #networks:
           # - elastic
        depends_on:
            -  financial-transactions-api-elasticsearch
volumes:
     financial-transaction-api-esdata-test:
        driver: local

#networks:
 # elastic:
 #   driver: bridge
