version: "3.2"

services:
  financial-transactions-api:
    image: financial-transactions-api
    build:
      context: .
      dockerfile: FinancialTransactionsApi/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
      - Sns_LocalMode=true
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - REQUIRED_GOOGL_GROUPS=e2e-testing-development

  financial-transactions-api-test:
    image: financial-transactions-api-test
    build:
      context: .
      dockerfile: FinancialTransactionsApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
      - SONAR_TOKEN=${SONAR_TOKEN}
    environment:
      - CONNECTION_STRING=Host=postgres-test-database;Port=5432;Database=testdb;Username=postgres;Password=mypassword
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - Localstack_SnsServiceUrl=http://localstack:4566
    links:
      - localstack
      - postgres-test-database
 
  postgres-test-database:
    image: postgres:latest
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "6000:5432"
    env_file:
      - database.env
      
  localstack:
    image: localstack/localstack
    hostname: awslocal    
    ports:
      - "4566:4566"      
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1                  
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack      
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"