version: "3.2"

services:
  financial-transactions-api:
    image: financial-transactions-api
    build:
      context: FinancialTransactionsApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database

  financial-transactions-api-test:
    image: financial-transactions-api-test
    build:
      context: .
      dockerfile: FinancialTransactionsApi.Tests/Dockerfile
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database

  dynamodb-database:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
