version: "3.2"

services:
  financial-transactions-api:
    image: financial-transactions-api
    build:
      context: FinancialTransactionsApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database

  financial-transactions-api-test:
    image: financial-transactions-api-test
    build:
      context: .
      dockerfile: FinancialTransactionsApi.Tests/Dockerfile
    environment:
      - ELASTICSEARCH_DOMAIN_URL=http://test-elasticsearch:9200
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database
      - test-elasticsearch
    networks:
      - elastic
    depends_on:
      #- kibana
      - test-elasticsearch
  test-elasticsearch:
    image: test-elasticsearch
    container_name: test-elasticsearch
    build:
      context: .
      dockerfile: data/elasticsearch/Dockerfile
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata-test:/usr/share/elasticsearch/data
    networks:
      - elastic
      
  dynamodb-database:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
volumes:
    esdata-test:
        driver: local

networks:
  elastic:
    driver: bridge
